-- 添加新字段到case表
ALTER TABLE "case" ADD COLUMN IF NOT EXISTS "other_clients" CLOB;
ALTER TABLE "case" ADD COLUMN IF NOT EXISTS "procedure_levels" CLOB;
ALTER TABLE "case" ADD COLUMN IF NOT EXISTS "is_legal_aid" BOOLEAN;
ALTER TABLE "case" ADD COLUMN IF NOT EXISTS "fixed_fee" DECIMAL(15,2);
ALTER TABLE "case" ADD COLUMN IF NOT EXISTS "risk_ratio" DECIMAL(5,2);
ALTER TABLE "case" ADD COLUMN IF NOT EXISTS "risk_fee" DECIMAL(15,2);
ALTER TABLE "case" ADD COLUMN IF NOT EXISTS "fee_remark" VARCHAR(1000);
