package com.lawfirm.config;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

/**
 * H2 开发库兜底：卷宗暂存表、OCR 结果列长度。
 */
@Slf4j
@Component
@Order(0)
@RequiredArgsConstructor
public class CaseIntakePendingSchemaInitializer implements CommandLineRunner {

    private final JdbcTemplate jdbcTemplate;

    @Override
    public void run(String... args) {
        widenAiLogColumns();
        widenOcrResultColumn();
        try {
            jdbcTemplate.execute(
                    "CREATE TABLE IF NOT EXISTS \"case_intake_pending\" ("
                            + "\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                            + "\"created_at\" TIMESTAMP NOT NULL, "
                            + "\"updated_at\" TIMESTAMP NOT NULL, "
                            + "\"deleted\" BOOLEAN NOT NULL DEFAULT FALSE, "
                            + "\"approval_id\" BIGINT, "
                            + "\"case_id\" BIGINT, "
                            + "\"content_type\" VARCHAR(128), "
                            + "\"file_size\" BIGINT, "
                            + "\"original_filename\" VARCHAR(255) NOT NULL, "
                            + "\"recognition_json\" CLOB, "
                            + "\"remark\" VARCHAR(500), "
                            + "\"status\" VARCHAR(20) NOT NULL, "
                            + "\"stored_path\" VARCHAR(255) NOT NULL, "
                            + "\"user_id\" BIGINT NOT NULL"
                            + ")");
            log.info("已确保 case_intake_pending 表存在");
        } catch (Exception e) {
            log.error("创建 case_intake_pending 表失败，卷宗暂存将不可用: {}", e.getMessage());
        }
    }

    private void widenAiLogColumns() {
        for (String col : new String[]{"input_content", "output_content", "error_message"}) {
            try {
                jdbcTemplate.execute(
                        "ALTER TABLE \"ai_log\" ALTER COLUMN \"" + col + "\" CLOB");
                log.info("已扩展 ai_log.{} 为 CLOB", col);
            } catch (Exception e) {
                log.debug("ai_log.{} 列无需调整: {}", col, e.getMessage());
            }
        }
    }

    private void widenOcrResultColumn() {
        try {
            jdbcTemplate.execute(
                    "ALTER TABLE \"case_document\" ALTER COLUMN \"ocr_result\" CLOB");
            log.info("已扩展 case_document.ocr_result 为 CLOB");
        } catch (Exception e) {
            log.debug("case_document.ocr_result 列无需调整: {}", e.getMessage());
        }
    }
}
